### PR TITLE
Code Review Request - Tried to add logging and graceful shutdown

### PR DESCRIPTION
**Pull request by mrjbj**
tried to add pino for logging and also graceful shutdown for unhandled exceptions or rejections (or ctrl-c). I think it works but not sure what standard practices are here so would appreciate any comments if you have time. 

On a different note, looking forward to see how you incorporate react hooks w/apollo client into codeponder.  It also looks like you figured out a way to go generic "base resolvers" for find, which is cool.  I don't fully grok that yet, so perhaps an "update video" to go over that would be nice sometime.  Cheers, jbj

### CODE REVIEW

**Comment by mrjbj** [comment]
Thanks for the feedback!

**Comment by benawad** [comment]
If you want to make the changes, I'll merge it in. Otherwise I'll add the changes and merge in.

**Comment by mrjbj** [comment]
I think i was able to update the pull request to reflect your comments. pull request process is a new thing for me, so hope not a mess and comments welcome.   Cheers.

**Comment by benawad** [comment]
thanks

**Pull request merged**
