### PR TITLE
Refactor CodeFile component

### PR DESCRIPTION
**Pull request by onemen**
**Key changes for this pr**:
- codeFile renders much faster
- new question/reply are visible immediately after submitting the form
- remove prism-react-renderer - use prism directly
- add each line of highlighted code with dangerouslySetInnerHTML see RenderLine component
- Import prism from prismjs/components/prism-core fix the missing highlight see [#972](https://github.com/PrismJS/prism/issues/972) [#1020](https://github.com/PrismJS/prism/issues/1020)
- add CodeCard as ui component

**TODO**
- add button/checkbox to show/hide: next/previous question, all question, ...
- apply new form design
- reuse same question/reply form for QuestionSection and CodeFile

### CODE REVIEW

**Comment by benawad** [comment]
Nice work! I'll review this in a little bit

**Comment by benawad** [comment]
Looks good, I'll wait till your done to merge

**Comment by onemen** [comment]
### New form design, new badge button to show/hide discussion

_New form design with these new features:_

- Added title to question form, currently just to the form, you need to update the mutation.
- Added option to select start line by clicking with the mouse. The last line determined by the line that opened the form.

_New badge button to show/hide discussion (question + replies) added to last line for each question._

- Added header at the top of each discussion. The header contains the discussion title and identifier, (currently just a placeholder), and the line numbers associate to it.  
  Regarding the identifier I this you can apply running number like in Github

### Todo: (future pull request)

- Add sticky navbar above the code to show/hide all discussions, go to next/previous discussion.
- Reuse the form for QuestionSection.
- Add avatar and date to each comment in the discussion.

### Notice:

- Large files may take long time to render. See how github address [this issue](https://github.com/benawad/codeponder/blob/master/packages/web/github-schema2.json).
- Fix how you open image files. Github show the [image](https://github.com/benawad/codeponder/blob/master/assets/logo.png).

**Comment by benawad** [comment]
Awesome, I'm going to wait for you to finish the pr before continuing on more stuff.

**Comment by onemen** [comment]
Currently QuestionSection is only used from post.tsx.
When user is in this page no file where selected, do you want to add option to ask question that are not related to a file?
We need some drop down list to let the user choose a file.

**Comment by benawad** [comment]
No drop-down is necessary, if they are not on a file then the question is a generic one

**Comment by onemen** [comment]
I'v done with this PR. 
i hope to be able contribute Code-ponder more in the future.

i'v accidentally push none squashed branch, but i'm sure you can handle it . :)

**Comment by benawad** [comment]
Wow, this is fantastic. I'll check this out soon

**Pull request merged**
